name: antares_market
description: Antares Market by Alexschiopu and envx team
publish_to: 'none'
version: 1.0.4+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.0
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  connectivity_plus: ^1.0.3
  copy_with_extension: ^2.0.0
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  flutex: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_cache_manager: ^3.0.1
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.0.0
  get: ^4.1.4
  get_it: ^7.1.3
  image_picker: ^0.8.4
  json_annotation: ^4.0.1
  package_info_plus: ^1.0.3
  path_provider: ^2.0.1
  qr_flutter: ^4.0.0
  readmore: ^2.0.0
  shared_preferences: ^2.0.5
  sliding_up_panel: ^2.0.0+1
  select_form_field: ^2.2.0
  syncfusion_flutter_sliders: ^19.2.59


dev_dependencies:
  build_runner: ^2.0.2
  copy_with_extension_gen: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/translations/location/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay/SFProDisplay_Thin.ttf
          weight: 100
        - asset: assets/fonts/SFProDisplay/SFProDisplay_Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay/SFProDisplay_Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay/SFProDisplay_Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay/SFProDisplay_Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay/SFProDisplay_Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay/SFProDisplay_Black.ttf
          weight: 900
